# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitia < Formula
  desc "Generate Conventional Commits from the staged diff with a local model"
  homepage "https://github.com/guerrero/gitia"
  version "0.2.0"
  license "Unlicense"

  depends_on "git"
  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guerrero/gitia/releases/download/v0.2.0/gitia_0.2.0_darwin_amd64.tar.gz"
      sha256 "4680db48b702e172514ebffda0be377a3f8b9af125c48060071d79f45d6a8f48"

      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guerrero/gitia/releases/download/v0.2.0/gitia_0.2.0_darwin_arm64.tar.gz"
      sha256 "6ac6d63c0d2bf8c7e6394e46247d06d4f23c0d2572e106c494a4431193f6d74b"

      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guerrero/gitia/releases/download/v0.2.0/gitia_0.2.0_linux_amd64.tar.gz"
      sha256 "2d6a7262595c0b0809783c41ef4ff1c07a954f0a83fa78bfc41fbc88b8553a5a"
      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guerrero/gitia/releases/download/v0.2.0/gitia_0.2.0_linux_arm64.tar.gz"
      sha256 "e82d36d690bd73e3a75c8e677c0a83ac79a45aa6826e6cce989cf63b2a253cff"
      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
  end

  test do
    system "#{bin}/gitia", "--version"
  end
end
