# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitia < Formula
  desc "Generate Conventional Commits from the staged diff with a local model"
  homepage "https://github.com/guerrero/gitia"
  license "Unlicense"

  depends_on "git"
  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guerrero/gitia/releases/download/v0.3.0/gitia_0.3.0_darwin_amd64.tar.gz"
      sha256 "b543d57aa1c56414f0a9e1177c61bbcec0ec566a26d5933f861ac7528b3cecdc"

      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guerrero/gitia/releases/download/v0.3.0/gitia_0.3.0_darwin_arm64.tar.gz"
      sha256 "cf59efde02765468b53e88dcd19a2017c63b95d088787a38051fb22a1c73c4f1"

      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guerrero/gitia/releases/download/v0.3.0/gitia_0.3.0_linux_amd64.tar.gz"
      sha256 "300ab0af495b34dfaf5e7c48242054871b52e7cfa6d897eaa1e47492c0270eb5"
      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guerrero/gitia/releases/download/v0.3.0/gitia_0.3.0_linux_arm64.tar.gz"
      sha256 "2a05698864d97c2a2edb976d52058ec9ac5160841fa52befaa3937f486f5c3ba"
      define_method(:install) do
        bin.install "gitia"
        man1.install "man/gitia.1"
      end
    end
  end

  test do
    system "#{bin}/gitia", "--version"
  end
end
